server {
    listen       80;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html;

    # Gzip — уменьшает трафик, нагрузка на CPU минимальна
    gzip on;
    gzip_types text/css application/javascript text/html image/svg+xml;
    gzip_min_length 256;

    # Кэширование статики
    location ~* \.(css|js|svg|png|jpg|jpeg|webp|ico|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
